test:
- sim_data/partnet_mobility/Microwave/7265/joint_0_bg/view_0/
- sim_data/partnet_mobility/Microwave/7265/joint_0_bg/view_1/
- sim_data/partnet_mobility/Refrigerator/10867/joint_0_bg/view_1/
- sim_data/partnet_mobility/Refrigerator/11304/joint_1_bg/view_0/
- sim_data/partnet_mobility/Refrigerator/11304/joint_0_bg/view_0/
- sim_data/partnet_mobility/Refrigerator/10143/joint_0_bg/view_1/
- sim_data/partnet_mobility/Refrigerator/10373/joint_0_bg/view_0/
- sim_data/partnet_mobility/Dishwasher/12562/joint_0_bg/view_1/
- sim_data/partnet_mobility/Dishwasher/12531/joint_0_bg/view_1/
- sim_data/partnet_mobility/Dishwasher/12552/joint_0_bg/view_0/
- sim_data/partnet_mobility/Dishwasher/12552/joint_0_bg/view_1/
- sim_data/partnet_mobility/Dishwasher/11700/joint_0_bg/view_1/
- sim_data/partnet_mobility/Dishwasher/12071/joint_0_bg/view_0/
- sim_data/partnet_mobility/Dishwasher/12565/joint_1_bg/view_0/
- sim_data/partnet_mobility/StorageFurniture/41510/joint_1_bg/view_1/
- sim_data/partnet_mobility/StorageFurniture/45132/joint_2_bg/view_0/
- sim_data/partnet_mobility/StorageFurniture/45146/joint_0_bg/view_0/
- sim_data/partnet_mobility/StorageFurniture/44962/joint_2_bg/view_1/
- sim_data/partnet_mobility/StorageFurniture/44781/joint_0_bg/view_1/
- sim_data/partnet_mobility/StorageFurniture/44817/joint_1_bg/view_1/
- sim_data/partnet_mobility/StorageFurniture/45001/joint_1_bg/view_0/
- sim_data/partnet_mobility/StorageFurniture/40453/joint_1_bg/view_1/
- sim_data/partnet_mobility/StorageFurniture/35059/joint_0_bg/view_0/
- sim_data/partnet_mobility/StorageFurniture/41083/joint_3_bg/view_1/
- sim_data/partnet_mobility/WashingMachine/103490/joint_0_bg/view_0/
- sim_data/partnet_mobility/WashingMachine/103778/joint_0_bg/view_0/
- sim_data/partnet_mobility/WashingMachine/103351/joint_0_bg/view_0/
- sim_data/partnet_mobility/WashingMachine/103528/joint_0_bg/view_1/
- sim_data/partnet_mobility/Scissors/10973/joint_0_bg/view_1/
- sim_data/partnet_mobility/Scissors/10895/joint_1_bg/view_0/
- sim_data/partnet_mobility/Scissors/10495/joint_0_bg/view_1/
- sim_data/partnet_mobility/Scissors/10567/joint_0_bg/view_0/
- sim_data/partnet_mobility/Scissors/10559/joint_0_bg/view_1/
- sim_data/partnet_mobility/Scissors/10558/joint_0_bg/view_0/
- sim_data/partnet_mobility/Stapler/103283/joint_1_bg/view_1/
- sim_data/partnet_mobility/Stapler/103273/joint_1_bg/view_1/
- sim_data/partnet_mobility/Table/23372/joint_1_bg/view_1/
- sim_data/partnet_mobility/Table/22433/joint_1_bg/view_0/
- sim_data/partnet_mobility/Table/22433/joint_0_bg/view_0/
- sim_data/partnet_mobility/Table/22433/joint_0_bg/view_1/
- sim_data/partnet_mobility/Table/22367/joint_2_bg/view_0/
- sim_data/partnet_mobility/Table/22367/joint_0_bg/view_0/
- sim_data/partnet_mobility/Table/19898/joint_4_bg/view_1/
- sim_data/partnet_mobility/Table/19898/joint_1_bg/view_1/
- sim_data/partnet_mobility/Table/19898/joint_3_bg/view_0/
- sim_data/partnet_mobility/Table/26525/joint_0_bg/view_1/
- sim_data/partnet_mobility/Table/19855/joint_0_bg/view_1/
- sim_data/partnet_mobility/Table/20985/joint_1_bg/view_0/
- sim_data/partnet_mobility/Table/26608/joint_0_bg/view_1/
- sim_data/partnet_mobility/Table/23807/joint_1_bg/view_1/
- sim_data/partnet_mobility/Table/26657/joint_1_bg/view_0/
- sim_data/partnet_mobility/Table/22339/joint_0_bg/view_1/
- sim_data/partnet_mobility/Table/22241/joint_0_bg/view_1/
- sim_data/partnet_mobility/Table/20745/joint_0_bg/view_1/
- sim_data/partnet_mobility/Table/19179/joint_1_bg/view_1/
- sim_data/partnet_mobility/Table/27267/joint_0_bg/view_1/
- sim_data/partnet_mobility/Table/23724/joint_2_bg/view_0/
- sim_data/partnet_mobility/Table/23724/joint_0_bg/view_1/
- sim_data/partnet_mobility/Box/100664/joint_0_bg/view_1/
- sim_data/partnet_mobility/USB/100072/joint_0_bg/view_0/
- sim_data/partnet_mobility/USB/101886/joint_0_bg/view_0/
- sim_data/partnet_mobility/USB/100087/joint_0_bg/view_0/
- sim_data/partnet_mobility/USB/100106/joint_0_bg/view_1/
- sim_data/partnet_mobility/USB/100071/joint_0_bg/view_1/
- sim_data/partnet_mobility/USB/100128/joint_0_bg/view_1/
- sim_data/partnet_mobility/USB/100133/joint_0_bg/view_0/
- sim_data/partnet_mobility/USB/100092/joint_0_bg/view_0/
- sim_data/partnet_mobility/USB/100068/joint_0_bg/view_0/
- sim_data/partnet_mobility/USB/101948/joint_0_bg/view_1/
- sim_data/partnet_mobility/Laptop/10306/joint_1_bg/view_1/
- sim_data/partnet_mobility/Laptop/10356/joint_0_bg/view_1/
- sim_data/partnet_mobility/Laptop/9987/joint_0_bg/view_1/
- sim_data/partnet_mobility/Laptop/10040/joint_1_bg/view_0/